global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
route:
  receiver: 'telepush'
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

inhibit_rules:
- source_matchers:
    - severity="critical"
  target_matchers:
    - severity="warning"
  equal: ['alertname', 'dev', 'instance']

receivers:
- name: 'telepush'
  webhook_configs:
   - url: 'https://telepush.dev/api/inlets/alertmanager/xxxxx'