  version: "2"
  services:
    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      volumes:
        - grafana-data:/var/lib/grafana
        - grafana-configs:/etc/grafana

    prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - prom-data:/prometheus
        - prom-configs:/etc/prometheus

    node-exporter:
      image: prom/node-exporter:latest
      ports:
        - "9100:9100"
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude'
        - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

    alertmanager:
      image: prom/alertmanager:latest
      ports:
        - "9093:9093"
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/alertmanager'

    blackbox:
      image: prom/blackbox-exporter:latest
      ports:
        - "9115:9115"
      volumes:
        - "./config:/config"
      command:
        - "--config.file=/etc/blackbox_exporter/config.yml"

  volumes:
    grafana-data:
    grafana-configs:
    prom-data:
    prom-configs:


